const raw_csv_data = [
    {
        "Timestamp": "1/14/2020 12:48:24",
        "Alias": "Hannah Abbott ",
        "What is your Major?": "Graphic Design",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "GameDesign",
        "How would you rate your Information Visualization skills?": 4,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 3,
        "How would you rate your drawing and artistic skills?": 4,
        "How would you rate your computer usage skills?": 10,
        "How would you rate your programming skills?": 4,
        "How would you rate your computer graphics programming skills?": 6,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 3,
        "How would you rate your communication skills?": 6,
        "How would you rate your collaboration skills?": 10,
        "How would you rate your code repository skills?": 6
    },
    {
        "Timestamp": "1/14/2020 17:07:56",
        "Alias": "Ludo Bagman ",
        "What is your Major?": "Information and Network Engineering",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "My main general interest is music. Recently I have been reading a book with a lot of data representations and it reminded me that data visualization is something I would like to learn more about (also because I like design). My main technical interest is multimedia processing because I like applied maths and multimedia analysis (originally I started my bachelor because of audio, but now I actually prefer image).",
        "How would you rate your Information Visualization skills?": 4,
        "How would you rate your statistical skills?": 8,
        "How would you rate your mathematics skills?": 6,
        "How would you rate your drawing and artistic skills?": 4,
        "How would you rate your computer usage skills?": 7,
        "How would you rate your programming skills?": 6,
        "How would you rate your computer graphics programming skills?": 4,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 1,
        "How would you rate your communication skills?": 10,
        "How would you rate your collaboration skills?": 5,
        "How would you rate your code repository skills?": 9
    },
    {
        "Timestamp": "1/14/2020 21:09:58",
        "Alias": "Bathilda Bagshot ",
        "What is your Major?": "Computer Science, Human-Computer Interaction ",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Travel, admire landscapes, photography, understand mass and companies market choices (e.g. The real reasons why Instagram hides \"likes\" number on its app, thy people love a certain brand and what it gives to them), UI design, understand user needs and experience, slow reading, free climbing, play electric bass guitar, manage a summer camp and be involved as an entertainer.",
        "How would you rate your Information Visualization skills?": 3,
        "How would you rate your statistical skills?": 2,
        "How would you rate your mathematics skills?": 3,
        "How would you rate your drawing and artistic skills?": 4,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 6,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 3,
        "How would you rate your communication skills?": 6,
        "How would you rate your collaboration skills?": 10,
        "How would you rate your code repository skills?": 5
    },
    {
        "Timestamp": "1/15/2020 10:54:13",
        "Alias": "Katie Bell ",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I've been a software developer for about 12 years, and I'm looking to make a career change into more research related work. I am also a martial artist and an (almost) certified martial arts instructor, and a mediocre bass and guitar player.",
        "How would you rate your Information Visualization skills?": 8,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 6,
        "How would you rate your drawing and artistic skills?": 6,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 10,
        "How would you rate your computer graphics programming skills?": 5,
        "How would you rate your human-computer interaction programming skills?": 5,
        "How would you rate your user experience evaluation skills?": 4,
        "How would you rate your communication skills?": 4,
        "How would you rate your collaboration skills?": 4,
        "How would you rate your code repository skills?": 8
    },
    {
        "Timestamp": "1/15/2020 13:28:41",
        "Alias": "Cuthbert Binns",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Gaming, Reddit, Instagram, CrossFit",
        "How would you rate your Information Visualization skills?": 6,
        "How would you rate your statistical skills?": 5,
        "How would you rate your mathematics skills?": 6,
        "How would you rate your drawing and artistic skills?": 4,
        "How would you rate your computer usage skills?": 9,
        "How would you rate your programming skills?": 8,
        "How would you rate your computer graphics programming skills?": 8,
        "How would you rate your human-computer interaction programming skills?": 6,
        "How would you rate your user experience evaluation skills?": 4,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 7,
        "How would you rate your code repository skills?": 8
    },
    {
        "Timestamp": "1/15/2020 15:44:03",
        "Alias": "Phineas Nigellus Black",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Movies, music, gym (going to the supermarket) ",
        "How would you rate your Information Visualization skills?": 3,
        "How would you rate your statistical skills?": 5,
        "How would you rate your mathematics skills?": 6,
        "How would you rate your drawing and artistic skills?": 1,
        "How would you rate your computer usage skills?": 7,
        "How would you rate your programming skills?": 7,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 3,
        "How would you rate your user experience evaluation skills?": 4,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 2
    },
    {
        "Timestamp": "1/15/2020 16:46:55",
        "Alias": "Sirius Black",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Movies, games, cooking",
        "How would you rate your Information Visualization skills?": 2,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 4,
        "How would you rate your computer usage skills?": 7,
        "How would you rate your programming skills?": 4,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 2,
        "How would you rate your user experience evaluation skills?": 3,
        "How would you rate your communication skills?": 5,
        "How would you rate your collaboration skills?": 5,
        "How would you rate your code repository skills?": 3
    },
    {
        "Timestamp": "1/15/2020 17:04:14",
        "Alias": "Amelia Bones ",
        "What is your Major?": "Human-Computer Interaction, Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I love playing computer games my favorite game is Cities skyline, close followed by Dota 2. I love UX-design, and smart solutions within the design. I wish I was the one who invented the green button on the phone when you want to call some one. I have worked mostly with web pages and apps. I also work part time for the Sas Scandinavian Airlines were I help them gater and present data from there big database in a way that makes sense and can easily be understood and I love it. My main tool at work is power bi, sql and excel",
        "How would you rate your Information Visualization skills?": 5,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 7,
        "How would you rate your drawing and artistic skills?": 2,
        "How would you rate your computer usage skills?": 9,
        "How would you rate your programming skills?": 4,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 3,
        "How would you rate your user experience evaluation skills?": 4,
        "How would you rate your communication skills?": 9,
        "How would you rate your collaboration skills?": 7,
        "How would you rate your code repository skills?": 7
    },
    {
        "Timestamp": "1/15/2020 17:12:57",
        "Alias": "Susan Bones ",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Sports, stock, software development, business",
        "How would you rate your Information Visualization skills?": 3,
        "How would you rate your statistical skills?": 4,
        "How would you rate your mathematics skills?": 4,
        "How would you rate your drawing and artistic skills?": 5,
        "How would you rate your computer usage skills?": 9,
        "How would you rate your programming skills?": 6,
        "How would you rate your computer graphics programming skills?": 3,
        "How would you rate your human-computer interaction programming skills?": 5,
        "How would you rate your user experience evaluation skills?": 4,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 5
    },
    {
        "Timestamp": "1/15/2020 17:14:24",
        "Alias": "Terry Boot",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Game development",
        "How would you rate your Information Visualization skills?": 1,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 7,
        "How would you rate your computer usage skills?": 9,
        "How would you rate your programming skills?": 6,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 3,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 8
    },
    {
        "Timestamp": "1/15/2020 17:27:37",
        "Alias": "Lavender Brown",
        "What is your Major?": "Human-Computer Interaction, Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I like to program in general, especially front end. On my spare time I go to the gym and hang with friends. ",
        "How would you rate your Information Visualization skills?": 2,
        "How would you rate your statistical skills?": 2,
        "How would you rate your mathematics skills?": 4,
        "How would you rate your drawing and artistic skills?": 5,
        "How would you rate your computer usage skills?": 5,
        "How would you rate your programming skills?": 5,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 3,
        "How would you rate your user experience evaluation skills?": 2,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 3
    },
    {
        "Timestamp": "1/15/2020 17:30:22",
        "Alias": "Millicent Bulstrode",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "My main interest is music, as a hobby I regularly play with a swing orchestra. I'm also interested in how far technology can reach in making people interact with it and how people can interact among themselves using technology, hence my decisione to join a interactive technology related faculty.",
        "How would you rate your Information Visualization skills?": 3,
        "How would you rate your statistical skills?": 1,
        "How would you rate your mathematics skills?": 6,
        "How would you rate your drawing and artistic skills?": 5,
        "How would you rate your computer usage skills?": 5,
        "How would you rate your programming skills?": 2,
        "How would you rate your computer graphics programming skills?": 4,
        "How would you rate your human-computer interaction programming skills?": 3,
        "How would you rate your user experience evaluation skills?": 4,
        "How would you rate your communication skills?": 6,
        "How would you rate your collaboration skills?": 4,
        "How would you rate your code repository skills?": 1
    },
    {
        "Timestamp": "1/15/2020 17:31:19",
        "Alias": "Charity Burbage",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I like painting with oil and acrylics. I work as an app developer but Will finish my masters anyway. The app I am working with is mostly about visualising data, with d3 for instance. Looking forward to become better at it",
        "How would you rate your Information Visualization skills?": 5,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 4,
        "How would you rate your drawing and artistic skills?": 8,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 7,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 4,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 8
    },
    {
        "Timestamp": "1/15/2020 17:37:47",
        "Alias": "Frank Bryce",
        "What is your Major?": "Human-Computer Interaction, Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I like programming especially front-end! ",
        "How would you rate your Information Visualization skills?": 2,
        "How would you rate your statistical skills?": 2,
        "How would you rate your mathematics skills?": 4,
        "How would you rate your drawing and artistic skills?": 1,
        "How would you rate your computer usage skills?": 5,
        "How would you rate your programming skills?": 5,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 3,
        "How would you rate your user experience evaluation skills?": 3,
        "How would you rate your communication skills?": 8,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 2
    },
    {
        "Timestamp": "1/15/2020 17:43:44",
        "Alias": "Alecto Carrow",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Game development, figure skating, playing games",
        "How would you rate your Information Visualization skills?": 4,
        "How would you rate your statistical skills?": 5,
        "How would you rate your mathematics skills?": 8,
        "How would you rate your drawing and artistic skills?": 4,
        "How would you rate your computer usage skills?": 9,
        "How would you rate your programming skills?": 7,
        "How would you rate your computer graphics programming skills?": 5,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 3,
        "How would you rate your communication skills?": 9,
        "How would you rate your collaboration skills?": 4,
        "How would you rate your code repository skills?": 7
    },
    {
        "Timestamp": "1/15/2020 17:45:59",
        "Alias": "Amycus Carrow",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I like art, painting, drawing and work with Photoshop in my spare time. I want to learn more programming, especially JavaScript at the moment. ",
        "How would you rate your Information Visualization skills?": 5,
        "How would you rate your statistical skills?": 1,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 9,
        "How would you rate your computer usage skills?": 9,
        "How would you rate your programming skills?": 5,
        "How would you rate your computer graphics programming skills?": 5,
        "How would you rate your human-computer interaction programming skills?": 5,
        "How would you rate your user experience evaluation skills?": 5,
        "How would you rate your communication skills?": 10,
        "How would you rate your collaboration skills?": 10,
        "How would you rate your code repository skills?": 5
    },
    {
        "Timestamp": "1/15/2020 17:49:32",
        "Alias": "Reginald Cattermole",
        "What is your Major?": "Human-Computer Interaction",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "My interests are design(in all forms and shapes) and dancing :)",
        "How would you rate your Information Visualization skills?": 2,
        "How would you rate your statistical skills?": 4,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 7,
        "How would you rate your computer usage skills?": 10,
        "How would you rate your programming skills?": 7,
        "How would you rate your computer graphics programming skills?": 6,
        "How would you rate your human-computer interaction programming skills?": 6,
        "How would you rate your user experience evaluation skills?": 8,
        "How would you rate your communication skills?": 10,
        "How would you rate your collaboration skills?": 10,
        "How would you rate your code repository skills?": 5
    },
    {
        "Timestamp": "1/15/2020 18:27:24",
        "Alias": "Mary Cattermole ",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I like programming, especially web programming. I am also into sports and nutrition.",
        "How would you rate your Information Visualization skills?": 2,
        "How would you rate your statistical skills?": 2,
        "How would you rate your mathematics skills?": 4,
        "How would you rate your drawing and artistic skills?": 1,
        "How would you rate your computer usage skills?": 6,
        "How would you rate your programming skills?": 5,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 2,
        "How would you rate your communication skills?": 10,
        "How would you rate your collaboration skills?": 7,
        "How would you rate your code repository skills?": 9
    },
    {
        "Timestamp": "1/15/2020 18:45:35",
        "Alias": "Cho Chang ",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Photography, kick-boxing, craft beer:)",
        "How would you rate your Information Visualization skills?": 4,
        "How would you rate your statistical skills?": 2,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 1,
        "How would you rate your computer usage skills?": 7,
        "How would you rate your programming skills?": 5,
        "How would you rate your computer graphics programming skills?": 5,
        "How would you rate your human-computer interaction programming skills?": 5,
        "How would you rate your user experience evaluation skills?": 3,
        "How would you rate your communication skills?": 8,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 6
    },
    {
        "Timestamp": "1/15/2020 19:25:14",
        "Alias": "Penelope Clearwater ",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I like to analyse data and present them in visually interesting ways. I read books and news articles. ",
        "How would you rate your Information Visualization skills?": 2,
        "How would you rate your statistical skills?": 4,
        "How would you rate your mathematics skills?": 2,
        "How would you rate your drawing and artistic skills?": 4,
        "How would you rate your computer usage skills?": 5,
        "How would you rate your programming skills?": 5,
        "How would you rate your computer graphics programming skills?": 2,
        "How would you rate your human-computer interaction programming skills?": 2,
        "How would you rate your user experience evaluation skills?": 4,
        "How would you rate your communication skills?": 8,
        "How would you rate your collaboration skills?": 5,
        "How would you rate your code repository skills?": 3
    },
    {
        "Timestamp": "1/16/2020 10:53:16",
        "Alias": "Michael Corner",
        "What is your Major?": "Human-Computer Interaction, Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I love to work out, eat good food and skiing, among other things. I'm mostly interested in design at a higher level, service- and concept design in relation to sustainability. ",
        "How would you rate your Information Visualization skills?": 2,
        "How would you rate your statistical skills?": 6,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 7,
        "How would you rate your computer usage skills?": 4,
        "How would you rate your programming skills?": 1,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 2,
        "How would you rate your user experience evaluation skills?": 8,
        "How would you rate your communication skills?": 10,
        "How would you rate your collaboration skills?": 9,
        "How would you rate your code repository skills?": 7
    },
    {
        "Timestamp": "1/16/2020 10:59:45",
        "Alias": "Vincent Crabbe",
        "What is your Major?": "Human-Computer Interaction, Graphic Design",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Fitness / Hiking / Guitar",
        "How would you rate your Information Visualization skills?": 3,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 7,
        "How would you rate your drawing and artistic skills?": 3,
        "How would you rate your computer usage skills?": 7,
        "How would you rate your programming skills?": 3,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 3,
        "How would you rate your user experience evaluation skills?": 1,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 10,
        "How would you rate your code repository skills?": 6
    },
    {
        "Timestamp": "1/16/2020 12:28:31",
        "Alias": "Colin Creevey",
        "What is your Major?": "Mathematics, Statistics",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I am super interested in data and how it can be used to find underlying trends and patterns. I am also interested in environmental issues and equality questions. When it comes to hobbies I enjoy hiking and adventures in nature as well as traveling and taking care of my plants. Food is also a huge interest for me.",
        "How would you rate your Information Visualization skills?": 4,
        "How would you rate your statistical skills?": 7,
        "How would you rate your mathematics skills?": 7,
        "How would you rate your drawing and artistic skills?": 6,
        "How would you rate your computer usage skills?": 7,
        "How would you rate your programming skills?": 5,
        "How would you rate your computer graphics programming skills?": 2,
        "How would you rate your human-computer interaction programming skills?": 2,
        "How would you rate your user experience evaluation skills?": 3,
        "How would you rate your communication skills?": 9,
        "How would you rate your collaboration skills?": 9,
        "How would you rate your code repository skills?": 2
    },
    {
        "Timestamp": "1/16/2020 14:15:24",
        "Alias": "Fleur Delacour ",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Interested in making computer games.",
        "How would you rate your Information Visualization skills?": 2,
        "How would you rate your statistical skills?": 7,
        "How would you rate your mathematics skills?": 7,
        "How would you rate your drawing and artistic skills?": 9,
        "How would you rate your computer usage skills?": 9,
        "How would you rate your programming skills?": 8,
        "How would you rate your computer graphics programming skills?": 4,
        "How would you rate your human-computer interaction programming skills?": 9,
        "How would you rate your user experience evaluation skills?": 8,
        "How would you rate your communication skills?": 9,
        "How would you rate your collaboration skills?": 9,
        "How would you rate your code repository skills?": 9
    },
    {
        "Timestamp": "1/16/2020 14:21:15",
        "Alias": "Amos Diggory",
        "What is your Major?": "Visual Computing",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "movies & tv, travelling, geography, science, art",
        "How would you rate your Information Visualization skills?": 6,
        "How would you rate your statistical skills?": 5,
        "How would you rate your mathematics skills?": 6,
        "How would you rate your drawing and artistic skills?": 1,
        "How would you rate your computer usage skills?": 7,
        "How would you rate your programming skills?": 7,
        "How would you rate your computer graphics programming skills?": 8,
        "How would you rate your human-computer interaction programming skills?": 7,
        "How would you rate your user experience evaluation skills?": 9,
        "How would you rate your communication skills?": 9,
        "How would you rate your collaboration skills?": 6,
        "How would you rate your code repository skills?": 7
    },
    {
        "Timestamp": "1/16/2020 15:19:18",
        "Alias": "Albus Dumbledore",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "My main interests outside of school are cooking, music (consuming, I'm not talented enough to create), and reading. I occasionally play video games or exercise, but they're not really \"passions\"",
        "How would you rate your Information Visualization skills?": 5,
        "How would you rate your statistical skills?": 8,
        "How would you rate your mathematics skills?": 8,
        "How would you rate your drawing and artistic skills?": 1,
        "How would you rate your computer usage skills?": 7,
        "How would you rate your programming skills?": 5,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 5,
        "How would you rate your user experience evaluation skills?": 7,
        "How would you rate your communication skills?": 9,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 8
    },
    {
        "Timestamp": "1/16/2020 15:36:07",
        "Alias": "Seamus Finnigan",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I'm interested in pretty much everything relating to the brain, cognition, and consciousness: neuroscience, philosophy, psychology, information technology. I spend most of my free time on nurturing these interests. I also like to listen to a lot of music (mostly hip hop) and sometimes play the piano.",
        "How would you rate your Information Visualization skills?": 3,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 7,
        "How would you rate your drawing and artistic skills?": 3,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 7,
        "How would you rate your computer graphics programming skills?": 2,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 2,
        "How would you rate your communication skills?": 8,
        "How would you rate your collaboration skills?": 7,
        "How would you rate your code repository skills?": 6
    },
    {
        "Timestamp": "1/16/2020 15:41:57",
        "Alias": "Marcus Flint",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "From a career perspective, I am interested in UX design and frontend development. Art is a hobby. ",
        "How would you rate your Information Visualization skills?": 2,
        "How would you rate your statistical skills?": 2,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 8,
        "How would you rate your computer usage skills?": 6,
        "How would you rate your programming skills?": 4,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 3,
        "How would you rate your user experience evaluation skills?": 2,
        "How would you rate your communication skills?": 10,
        "How would you rate your collaboration skills?": 6,
        "How would you rate your code repository skills?": 6
    },
    {
        "Timestamp": "1/16/2020 15:43:19",
        "Alias": "Filius Flitwick ",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "",
        "How would you rate your Information Visualization skills?": 5,
        "How would you rate your statistical skills?": 7,
        "How would you rate your mathematics skills?": 7,
        "How would you rate your drawing and artistic skills?": 6,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 8,
        "How would you rate your computer graphics programming skills?": 5,
        "How would you rate your human-computer interaction programming skills?": 7,
        "How would you rate your user experience evaluation skills?": 7,
        "How would you rate your communication skills?": 9,
        "How would you rate your collaboration skills?": 9,
        "How would you rate your code repository skills?": 9
    },
    {
        "Timestamp": "1/16/2020 16:20:08",
        "Alias": "Cornelius Fudge",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I like machine learning and programming. I am interested in being active and powerlifting. ",
        "How would you rate your Information Visualization skills?": 1,
        "How would you rate your statistical skills?": 8,
        "How would you rate your mathematics skills?": 4,
        "How would you rate your drawing and artistic skills?": 3,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 7,
        "How would you rate your computer graphics programming skills?": 3,
        "How would you rate your human-computer interaction programming skills?": 1,
        "How would you rate your user experience evaluation skills?": 1,
        "How would you rate your communication skills?": 4,
        "How would you rate your collaboration skills?": 5,
        "How would you rate your code repository skills?": 7
    },
    {
        "Timestamp": "1/16/2020 16:53:39",
        "Alias": "Gellert Grindelwald ",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I like to create stuff. It’s the process and problem solving that I find interesting. Medium, tools or purpose doesn't really matter.",
        "How would you rate your Information Visualization skills?": 3,
        "How would you rate your statistical skills?": 2,
        "How would you rate your mathematics skills?": 4,
        "How would you rate your drawing and artistic skills?": 8,
        "How would you rate your computer usage skills?": 7,
        "How would you rate your programming skills?": 3,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 3,
        "How would you rate your user experience evaluation skills?": 3,
        "How would you rate your communication skills?": 3,
        "How would you rate your collaboration skills?": 4,
        "How would you rate your code repository skills?": 5
    },
    {
        "Timestamp": "1/16/2020 23:04:05",
        "Alias": "Godric Gryffindor ",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "",
        "How would you rate your Information Visualization skills?": 2,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 6,
        "How would you rate your computer usage skills?": 10,
        "How would you rate your programming skills?": 5,
        "How would you rate your computer graphics programming skills?": 3,
        "How would you rate your human-computer interaction programming skills?": 2,
        "How would you rate your user experience evaluation skills?": 7,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 3,
        "How would you rate your code repository skills?": 2
    },
    {
        "Timestamp": "1/17/2020 11:08:25",
        "Alias": "Rubeus Hagrid ",
        "What is your Major?": "Computer Science, Transport Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Urban mobility, spatio-temporal clustering, visualization, family",
        "How would you rate your Information Visualization skills?": 6,
        "How would you rate your statistical skills?": 7,
        "How would you rate your mathematics skills?": 6,
        "How would you rate your drawing and artistic skills?": 6,
        "How would you rate your computer usage skills?": 6,
        "How would you rate your programming skills?": 7,
        "How would you rate your computer graphics programming skills?": 4,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 2,
        "How would you rate your communication skills?": 4,
        "How would you rate your collaboration skills?": 4,
        "How would you rate your code repository skills?": 3
    },
    {
        "Timestamp": "1/17/2020 11:13:15",
        "Alias": "Rolanda Hooch ",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "My hobbies include: playing  music: both guitar and piano, anime, videogames. ",
        "How would you rate your Information Visualization skills?": 5,
        "How would you rate your statistical skills?": 4,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 5,
        "How would you rate your computer usage skills?": 6,
        "How would you rate your programming skills?": 6,
        "How would you rate your computer graphics programming skills?": 2,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 6,
        "How would you rate your communication skills?": 10,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 9
    },
    {
        "Timestamp": "1/17/2020 14:04:37",
        "Alias": "Helga Hufflepuff",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I am interested in music and play the piano, guitar, bass and sing. I have now started to translate this to media technology by learning about sound and music interaction through technology. I'm also a smart home enthusiast and have started to make my home smart, starting with lights and switches. ",
        "How would you rate your Information Visualization skills?": 4,
        "How would you rate your statistical skills?": 5,
        "How would you rate your mathematics skills?": 6,
        "How would you rate your drawing and artistic skills?": 3,
        "How would you rate your computer usage skills?": 7,
        "How would you rate your programming skills?": 6,
        "How would you rate your computer graphics programming skills?": 2,
        "How would you rate your human-computer interaction programming skills?": 6,
        "How would you rate your user experience evaluation skills?": 5,
        "How would you rate your communication skills?": 8,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 7
    },
    {
        "Timestamp": "1/17/2020 14:06:20",
        "Alias": "Hermione Granger",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Music and sound production",
        "How would you rate your Information Visualization skills?": 2,
        "How would you rate your statistical skills?": 5,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 1,
        "How would you rate your computer usage skills?": 7,
        "How would you rate your programming skills?": 4,
        "How would you rate your computer graphics programming skills?": 2,
        "How would you rate your human-computer interaction programming skills?": 5,
        "How would you rate your user experience evaluation skills?": 8,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 9,
        "How would you rate your code repository skills?": 5
    },
    {
        "Timestamp": "1/17/2020 15:24:36",
        "Alias": "Igor Karkaroff ",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "New topics interest me. Before I began studying Design I studied Computer Science; before that I studied Latin and Classical Civilizations. My favorite hobby is to find new hobbies - I have done a plethora of things including piano, archery, magic, massage, and dance.",
        "How would you rate your Information Visualization skills?": 1,
        "How would you rate your statistical skills?": 2,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 6,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 6,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 1,
        "How would you rate your user experience evaluation skills?": 4,
        "How would you rate your communication skills?": 9,
        "How would you rate your collaboration skills?": 10,
        "How would you rate your code repository skills?": 6
    },
    {
        "Timestamp": "1/17/2020 17:35:59",
        "Alias": "Viktor Krum",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Front end developing and web design ",
        "How would you rate your Information Visualization skills?": 6,
        "How would you rate your statistical skills?": 4,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 6,
        "How would you rate your computer usage skills?": 6,
        "How would you rate your programming skills?": 7,
        "How would you rate your computer graphics programming skills?": 4,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 6,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 6,
        "How would you rate your code repository skills?": 7
    },
    {
        "Timestamp": "1/17/2020 17:55:51",
        "Alias": "Silvanus Kettleburn ",
        "What is your Major?": "Media Technology, ICT",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Music, Art, Animals, Human rights, Environmental issues",
        "How would you rate your Information Visualization skills?": 4,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 4,
        "How would you rate your drawing and artistic skills?": 5,
        "How would you rate your computer usage skills?": 5,
        "How would you rate your programming skills?": 4,
        "How would you rate your computer graphics programming skills?": 2,
        "How would you rate your human-computer interaction programming skills?": 2,
        "How would you rate your user experience evaluation skills?": 5,
        "How would you rate your communication skills?": 10,
        "How would you rate your collaboration skills?": 6,
        "How would you rate your code repository skills?": 6
    },
    {
        "Timestamp": "1/17/2020 19:09:44",
        "Alias": "Bellatrix Lestrange",
        "What is your Major?": "Human-Computer Interaction",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I will be attracted by some creative ideas. I'm always searching for the newest, most interesting and unique products. I'm curious about the world and want to experience a lot of things in my life, such as parachute jumping and some other exciting sports.",
        "How would you rate your Information Visualization skills?": 5,
        "How would you rate your statistical skills?": 5,
        "How would you rate your mathematics skills?": 7,
        "How would you rate your drawing and artistic skills?": 6,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 2,
        "How would you rate your computer graphics programming skills?": 2,
        "How would you rate your human-computer interaction programming skills?": 3,
        "How would you rate your user experience evaluation skills?": 4,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 7
    },
    {
        "Timestamp": "1/17/2020 23:04:23",
        "Alias": "Neville Longbottom",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I like hanging out with friend and perhaps do some activity of some sort or play video games is a lot of fun. I also have a dog which includes long walks which I think is very nice. ",
        "How would you rate your Information Visualization skills?": 3,
        "How would you rate your statistical skills?": 4,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 5,
        "How would you rate your computer usage skills?": 6,
        "How would you rate your programming skills?": 5,
        "How would you rate your computer graphics programming skills?": 5,
        "How would you rate your human-computer interaction programming skills?": 5,
        "How would you rate your user experience evaluation skills?": 4,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 7,
        "How would you rate your code repository skills?": 3
    },
    {
        "Timestamp": "1/18/2020 0:28:48",
        "Alias": "Xenophilius Lovegood ",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I interested in music and something looks funny. I love singing, doing some sports and traveling.",
        "How would you rate your Information Visualization skills?": 4,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 7,
        "How would you rate your drawing and artistic skills?": 5,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 8,
        "How would you rate your computer graphics programming skills?": 2,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 5,
        "How would you rate your communication skills?": 9,
        "How would you rate your collaboration skills?": 7,
        "How would you rate your code repository skills?": 5
    },
    {
        "Timestamp": "1/18/2020 13:04:08",
        "Alias": "Remus Lupin",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "art, climbing, creative realization of hci",
        "How would you rate your Information Visualization skills?": 3,
        "How would you rate your statistical skills?": 1,
        "How would you rate your mathematics skills?": 4,
        "How would you rate your drawing and artistic skills?": 6,
        "How would you rate your computer usage skills?": 9,
        "How would you rate your programming skills?": 6,
        "How would you rate your computer graphics programming skills?": 4,
        "How would you rate your human-computer interaction programming skills?": 8,
        "How would you rate your user experience evaluation skills?": 7,
        "How would you rate your communication skills?": 3,
        "How would you rate your collaboration skills?": 6,
        "How would you rate your code repository skills?": 5
    },
    {
        "Timestamp": "1/18/2020 15:11:33",
        "Alias": "Draco Malfoy",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Basketball, Formula 1, travelling, photography, reading, JRR Tolkien",
        "How would you rate your Information Visualization skills?": 8,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 5,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 7,
        "How would you rate your computer graphics programming skills?": 5,
        "How would you rate your human-computer interaction programming skills?": 6,
        "How would you rate your user experience evaluation skills?": 6,
        "How would you rate your communication skills?": 10,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 8
    },
    {
        "Timestamp": "1/18/2020 17:33:00",
        "Alias": "Ernie Macmillan",
        "What is your Major?": "Human-Computer Interaction",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I am passionate about technology and self improvement. I meditate regularly.\nIn my free time I work out (gym and calisthenics), go running. I also enjoy reading.",
        "How would you rate your Information Visualization skills?": 3,
        "How would you rate your statistical skills?": 4,
        "How would you rate your mathematics skills?": 1,
        "How would you rate your drawing and artistic skills?": 1,
        "How would you rate your computer usage skills?": 10,
        "How would you rate your programming skills?": 10,
        "How would you rate your computer graphics programming skills?": 2,
        "How would you rate your human-computer interaction programming skills?": 1,
        "How would you rate your user experience evaluation skills?": 8,
        "How would you rate your communication skills?": 5,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 9
    },
    {
        "Timestamp": "1/19/2020 11:14:40",
        "Alias": "Minerva McGonagall",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Photography and design (interior, clothing, digital)",
        "How would you rate your Information Visualization skills?": 7,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 4,
        "How would you rate your drawing and artistic skills?": 8,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 6,
        "How would you rate your computer graphics programming skills?": 4,
        "How would you rate your human-computer interaction programming skills?": 7,
        "How would you rate your user experience evaluation skills?": 8,
        "How would you rate your communication skills?": 9,
        "How would you rate your collaboration skills?": 9,
        "How would you rate your code repository skills?": 9
    },
    {
        "Timestamp": "1/19/2020 12:22:38",
        "Alias": "Cormac McLaggen",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Music, movies, design, audio",
        "How would you rate your Information Visualization skills?": 2,
        "How would you rate your statistical skills?": 5,
        "How would you rate your mathematics skills?": 3,
        "How would you rate your drawing and artistic skills?": 3,
        "How would you rate your computer usage skills?": 3,
        "How would you rate your programming skills?": 2,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 1,
        "How would you rate your user experience evaluation skills?": 7,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 4
    },
    {
        "Timestamp": "1/19/2020 12:43:56",
        "Alias": "Graham Montague",
        "What is your Major?": "Graphic Design, Product Design",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "photography, videography, technology, science, arts, music, analog photography, basket, football, books, computers, make things ",
        "How would you rate your Information Visualization skills?": 3,
        "How would you rate your statistical skills?": 4,
        "How would you rate your mathematics skills?": 6,
        "How would you rate your drawing and artistic skills?": 8,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 2,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 3,
        "How would you rate your user experience evaluation skills?": 7,
        "How would you rate your communication skills?": 9,
        "How would you rate your collaboration skills?": 10,
        "How would you rate your code repository skills?": 3
    },
    {
        "Timestamp": "1/19/2020 15:16:26",
        "Alias": "Theodore Nott",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Computer games, music, snowboarding, nature, and more.",
        "How would you rate your Information Visualization skills?": 4,
        "How would you rate your statistical skills?": 5,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 8,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 6,
        "How would you rate your computer graphics programming skills?": 4,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 3,
        "How would you rate your communication skills?": 6,
        "How would you rate your collaboration skills?": 7,
        "How would you rate your code repository skills?": 9
    },
    {
        "Timestamp": "1/19/2020 16:16:48",
        "Alias": "Garrick Ollivander ",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I'm interested in how we can use technology in order to live more environmentally sustainable. My non-study related hobbies are cooking, reading, and spinning. ",
        "How would you rate your Information Visualization skills?": 1,
        "How would you rate your statistical skills?": 4,
        "How would you rate your mathematics skills?": 6,
        "How would you rate your drawing and artistic skills?": 3,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 5,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 2,
        "How would you rate your user experience evaluation skills?": 7,
        "How would you rate your communication skills?": 9,
        "How would you rate your collaboration skills?": 9,
        "How would you rate your code repository skills?": 7
    },
    {
        "Timestamp": "1/19/2020 16:25:18",
        "Alias": "Pansy Parkinson",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Videogames, boardgames, training, volleyball, painting, editing ",
        "How would you rate your Information Visualization skills?": 8,
        "How would you rate your statistical skills?": 8,
        "How would you rate your mathematics skills?": 7,
        "How would you rate your drawing and artistic skills?": 7,
        "How would you rate your computer usage skills?": 9,
        "How would you rate your programming skills?": 8,
        "How would you rate your computer graphics programming skills?": 8,
        "How would you rate your human-computer interaction programming skills?": 6,
        "How would you rate your user experience evaluation skills?": 6,
        "How would you rate your communication skills?": 8,
        "How would you rate your collaboration skills?": 9,
        "How would you rate your code repository skills?": 6
    },
    {
        "Timestamp": "1/19/2020 16:57:12",
        "Alias": "Peter Pettigrew ",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I would say my largest interest/hobby is movies, both new and old. Other than that I am also interested in plants and trying new things with my friends. ",
        "How would you rate your Information Visualization skills?": 4,
        "How would you rate your statistical skills?": 5,
        "How would you rate your mathematics skills?": 6,
        "How would you rate your drawing and artistic skills?": 2,
        "How would you rate your computer usage skills?": 6,
        "How would you rate your programming skills?": 3,
        "How would you rate your computer graphics programming skills?": 3,
        "How would you rate your human-computer interaction programming skills?": 3,
        "How would you rate your user experience evaluation skills?": 8,
        "How would you rate your communication skills?": 10,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 4
    },
    {
        "Timestamp": "1/19/2020 17:09:07",
        "Alias": "Antioch Peverell",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "* I'm studying my forth year at KTH\n* I have chosen the route of sustainable media technology in my bachelors\n* therefore been exposed more to humanities- than programming oriented courses\n* Deeply interested in Sustainability issues\n* interested in how to communicate data on sustainability efficiently",
        "How would you rate your Information Visualization skills?": 1,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 3,
        "How would you rate your drawing and artistic skills?": 5,
        "How would you rate your computer usage skills?": 4,
        "How would you rate your programming skills?": 1,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 1,
        "How would you rate your user experience evaluation skills?": 6,
        "How would you rate your communication skills?": 8,
        "How would you rate your collaboration skills?": 7,
        "How would you rate your code repository skills?": 3
    },
    {
        "Timestamp": "1/19/2020 17:28:43",
        "Alias": "Irma Pince",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Cats, TV series",
        "How would you rate your Information Visualization skills?": 4,
        "How would you rate your statistical skills?": 8,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 10,
        "How would you rate your computer usage skills?": 9,
        "How would you rate your programming skills?": 3,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 3,
        "How would you rate your user experience evaluation skills?": 7,
        "How would you rate your communication skills?": 6,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 1
    },
    {
        "Timestamp": "1/19/2020 18:20:03",
        "Alias": "Sturgis Podmore ",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "In terms of possible professional areas, I'm interested in news communication/reporting, free speech issues, language, streaming services, assistive technologies and most things relating to food.\nIn my spare time, I browse various Youtube content, play video games, listen to music (preferring progressive, psychedelic and folk rock) and hunt down the best grocery bargains.",
        "How would you rate your Information Visualization skills?": 2,
        "How would you rate your statistical skills?": 2,
        "How would you rate your mathematics skills?": 3,
        "How would you rate your drawing and artistic skills?": 3,
        "How would you rate your computer usage skills?": 4,
        "How would you rate your programming skills?": 1,
        "How would you rate your computer graphics programming skills?": 1,
        "How would you rate your human-computer interaction programming skills?": 2,
        "How would you rate your user experience evaluation skills?": 3,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 7,
        "How would you rate your code repository skills?": 2
    },
    {
        "Timestamp": "1/19/2020 20:05:46",
        "Alias": "Poppy Pomfrey ",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Creating stuff, listening to music, and dancing.",
        "How would you rate your Information Visualization skills?": 5,
        "How would you rate your statistical skills?": 4,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 3,
        "How would you rate your computer usage skills?": 7,
        "How would you rate your programming skills?": 7,
        "How would you rate your computer graphics programming skills?": 3,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 4,
        "How would you rate your communication skills?": 8,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 3
    },
    {
        "Timestamp": "1/19/2020 20:16:04",
        "Alias": "Harry Potter ",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "",
        "How would you rate your Information Visualization skills?": 4,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 7,
        "How would you rate your drawing and artistic skills?": 2,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 2,
        "How would you rate your computer graphics programming skills?": 3,
        "How would you rate your human-computer interaction programming skills?": 3,
        "How would you rate your user experience evaluation skills?": 3,
        "How would you rate your communication skills?": 3,
        "How would you rate your collaboration skills?": 8,
        "How would you rate your code repository skills?": 2
    },
    {
        "Timestamp": "1/19/2020 21:44:50",
        "Alias": "James Potter ",
        "What is your Major?": "Human-Computer Interaction",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I'm an exchange student from the Eindhoven University of Technology. I'm enrolled in the master program called HTI - Human Technology Interaction. I'm driven by shaping innovative designs so that they could solve currently existing, or future problems for society. My hobbies are skiing, windsurfing, and drawing.",
        "How would you rate your Information Visualization skills?": 4,
        "How would you rate your statistical skills?": 8,
        "How would you rate your mathematics skills?": 3,
        "How would you rate your drawing and artistic skills?": 8,
        "How would you rate your computer usage skills?": 5,
        "How would you rate your programming skills?": 1,
        "How would you rate your computer graphics programming skills?": 3,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 8,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 7,
        "How would you rate your code repository skills?": 2
    },
    {
        "Timestamp": "1/19/2020 22:13:53",
        "Alias": "Lily Potter",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Music, Fashion, Sports",
        "How would you rate your Information Visualization skills?": 4,
        "How would you rate your statistical skills?": 6,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 6,
        "How would you rate your computer usage skills?": 6,
        "How would you rate your programming skills?": 3,
        "How would you rate your computer graphics programming skills?": 4,
        "How would you rate your human-computer interaction programming skills?": 4,
        "How would you rate your user experience evaluation skills?": 7,
        "How would you rate your communication skills?": 8,
        "How would you rate your collaboration skills?": 9,
        "How would you rate your code repository skills?": 2
    },
    {
        "Timestamp": "1/19/2020 22:20:37",
        "Alias": "Quirinus Quirrell",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Photography, computer games, game development",
        "How would you rate your Information Visualization skills?": 6,
        "How would you rate your statistical skills?": 2,
        "How would you rate your mathematics skills?": 7,
        "How would you rate your drawing and artistic skills?": 8,
        "How would you rate your computer usage skills?": 9,
        "How would you rate your programming skills?": 7,
        "How would you rate your computer graphics programming skills?": 7,
        "How would you rate your human-computer interaction programming skills?": 7,
        "How would you rate your user experience evaluation skills?": 3,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 7,
        "How would you rate your code repository skills?": 6
    },
    {
        "Timestamp": "1/19/2020 22:41:14",
        "Alias": "Helena Ravenclaw",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "",
        "How would you rate your Information Visualization skills?": 7,
        "How would you rate your statistical skills?": 7,
        "How would you rate your mathematics skills?": 8,
        "How would you rate your drawing and artistic skills?": 8,
        "How would you rate your computer usage skills?": 7,
        "How would you rate your programming skills?": 5,
        "How would you rate your computer graphics programming skills?": 5,
        "How would you rate your human-computer interaction programming skills?": 6,
        "How would you rate your user experience evaluation skills?": 6,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 5,
        "How would you rate your code repository skills?": 5
    },
    {
        "Timestamp": "1/19/2020 22:51:57",
        "Alias": "Rowena Ravenclaw",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "I like listening to music and DJing. Movies, TV-shows, football (soccer) interest me.",
        "How would you rate your Information Visualization skills?": 6,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 4,
        "How would you rate your drawing and artistic skills?": 5,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 6,
        "How would you rate your computer graphics programming skills?": 2,
        "How would you rate your human-computer interaction programming skills?": 6,
        "How would you rate your user experience evaluation skills?": 6,
        "How would you rate your communication skills?": 7,
        "How would you rate your collaboration skills?": 3,
        "How would you rate your code repository skills?": 5
    },
    {
        "Timestamp": "1/19/2020 23:04:26",
        "Alias": "Tom Marvolo Riddle",
        "What is your Major?": "Media Technology",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "23 years old from Sweden, lived in Portugal for a year working with marketing. My hobbies include beauty and ice hockey. I am interested in developing my programming skills.",
        "How would you rate your Information Visualization skills?": 3,
        "How would you rate your statistical skills?": 3,
        "How would you rate your mathematics skills?": 5,
        "How would you rate your drawing and artistic skills?": 5,
        "How would you rate your computer usage skills?": 8,
        "How would you rate your programming skills?": 5,
        "How would you rate your computer graphics programming skills?": 2,
        "How would you rate your human-computer interaction programming skills?": 3,
        "How would you rate your user experience evaluation skills?": 5,
        "How would you rate your communication skills?": 10,
        "How would you rate your collaboration skills?": 10,
        "How would you rate your code repository skills?": 5
    },
    {
        "Timestamp": "1/19/2020 23:57:31",
        "Alias": "Demelza Robins ",
        "What is your Major?": "Computer Science",
        "Please, tell me about yourself. What interest you? Do you have any hobbies?": "Every lesson of computer science attracted my attention. I have many hobbies like running, , traveling, professional photography, watching movies and TV series, reading books, recording music, playing guitar etc.",
        "How would you rate your Information Visualization skills?": 3,
        "How would you rate your statistical skills?": 6,
        "How would you rate your mathematics skills?": 6,
        "How would you rate your drawing and artistic skills?": 4,
        "How would you rate your computer usage skills?": 10,
        "How would you rate your programming skills?": 7,
        "How would you rate your computer graphics programming skills?": 5,
        "How would you rate your human-computer interaction programming skills?": 5,
        "How would you rate your user experience evaluation skills?": 5,
        "How would you rate your communication skills?": 8,
        "How would you rate your collaboration skills?": 9,
        "How would you rate your code repository skills?": 8
    }
];

export interface Skills {
    informationVisualisation: number,
    statistics: number,
    mathematics: number,
    drawingAndArt: number,
    programming: number,
    computerGraphicsProgramming: number,
    humanComputerInteraction: number,
    userExperienceEvaluation: number,
    communication: number,
    collaboration: number,
    codeRepositoryKnowledge: number,
};


export interface Student {
    name: string,
    major: string,
    interests: string,
    skills: Skills,
};

export interface ProcessedSkills {
    math: number;
    programming: number;
    communication: number;
    HCI: number;
    visAndDrawing: number;
}

export interface ProcessedStudent {
    name: string,
    major: string,
    interests: string[],
    skills: ProcessedSkills,
    group: null | number,
    id: number
};

export interface Group {
    memberIds: number[],
}



const processedStudentData = function () {

    let processedStudentList: ProcessedStudent[] = raw_csv_data.map((student, index) => {

        let studentSkills: Skills = {
            informationVisualisation: student["How would you rate your Information Visualization skills?"] / 10,
            statistics: student["How would you rate your statistical skills?"] / 10,
            mathematics: student["How would you rate your mathematics skills?"] / 10,
            drawingAndArt: student["How would you rate your drawing and artistic skills?"] / 10,
            programming: student["How would you rate your programming skills?"] / 10,
            computerGraphicsProgramming: student["How would you rate your computer graphics programming skills?"] / 10,
            humanComputerInteraction: student["How would you rate your human-computer interaction programming skills?"] / 10,
            userExperienceEvaluation: student["How would you rate your user experience evaluation skills?"] / 10,
            communication: student["How would you rate your communication skills?"] / 10,
            collaboration: student["How would you rate your collaboration skills?"] / 10,
            codeRepositoryKnowledge: student["How would you rate your code repository skills?"] / 10,
        };

        let math = (studentSkills.mathematics + studentSkills.statistics) / 2;
        let programming = (studentSkills.programming + studentSkills.codeRepositoryKnowledge + studentSkills.computerGraphicsProgramming) / 3;
        let communication = (studentSkills.communication + studentSkills.collaboration) / 2;
        let HCI = studentSkills.humanComputerInteraction;
        let visAndDrawing = (studentSkills.informationVisualisation + studentSkills.informationVisualisation) / 2;

        let processedStudent: ProcessedStudent = {
            name: student.Alias,
            major: student["What is your Major?"],
            //interests: student["Please, tell me about yourself. What interest you? Do you have any hobbies?"].split(" "),
            interests: ['Dogs', 'Programming', 'Dancing'],
            skills: { math: math, programming: programming, communication: communication, HCI: HCI, visAndDrawing: visAndDrawing },
            group: null,
            id: index
        };


        return processedStudent;
    });

    return processedStudentList;
}();




export default processedStudentData;